---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-cafe-core
  labels:
    app: quarkus-cafe-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-cafe-core
  template:
    metadata:
      name: quarkus-cafe-core-deployment
      labels:
        app:  quarkus-cafe-core
        app.kubernetes.io/component: quarkus-cafe-core
        app.kubernetes.io/instance: quarkus-cafe-core
        app.kubernetes.io/part-of: quarkus-cafe
        quarkus-cafe: ""
        app.openshift.io/runtime-namespace: quarkus-cafe-demo
    spec:
      containers:
        - name: quarkus-cafe-core
          image: jeremydavis/quarkus-cafe-core:2.4.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_URLS
              value: cafe-cluster-kafka-bootstrap:9092
            - name: MONGO_DB
              value: cafedb
            - name: MONGO_URL
              value: mongodb://mongodb:mongodb@mongodb:27017/cafedb
            - name: MONGO_USERNAME
              value: mongodb
            - name: MONGO_PASSWORD
              value: mongodb