apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-cafe-core
spec:
  template:
    spec:
      containers:
        - name: quarkus-cafe-core
          env:
            - name: KAFKA_BOOTSTRAP_URLS
              value: cafe-cluster-kafka-bootstraaap:9092
            - name: MONGO_DB
              value: cafedb
            - name: MONGO_URL
              value: mongodb://mongodb:mongodb@mongodb:27017/cafedb
            - name: MONGO_USERNAME
              value: mongodb
            - name: MONGO_PASSWORD
              value: mongodb