apiVersion: v1
kind: Service
metadata:
  name: quarkus-cafe-barista
  labels:
    app:  quarkus-cafe-barista
spec:
  selector:
    app:  quarkus-cafe-barista
  type: ClusterIP
  ports:
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    - name: 9779-tcp
      port: 9779
      protocol: TCP
      targetPort: 9779