resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: jeremydavis/quarkus-cafe-kitchen
  newTag: 2.4.0
patchesStrategicMerge:
  - patch-env.yaml