---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-cafe-web
  labels:
    app: quarkus-cafe-web
spec:
  selector:
    app: quarkus-cafe-web
  type: ClusterIP
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080